language: python
sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_install:
  - cd ..; git clone https://github.com/workflowhub/workflow-schema
  - cd pegasus-traces

script:
  - find . -type f -name "*.json" > traces.txt
  - for trace_file in `cat traces.txt`; do
      python3 ../workflow-schema/validator.py -d ${trace_file};
      echo "";
    done
