language: python
sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_install:
  - cd ..; git clone https://github.com/workflowhub/workflow-schema
  - cd pegasus-traces

script:
  - pwd
  - echo "-----------------------------------------"
  - ls -lh
  - find . -type f -name "*.json"
